#!/usr/bin/ruby

require "rubybuild/ruby_build.rb"

class Main < RubyBuild
  def initialize
    super "silentbob"

    files = Dir["src/*.cxx"]
    @threads = 4

#    @debug_env[:ldflags] = "-L./ -ldl"
#    @release_env[:ldflags] = "-L./ -ldl"
    @debug_env[:include] = "-Iinclude"
    @release_env[:include] = "-Iinclude"

#    build_shared("liblibname.so", files)
    build_binary("silentbob", files)
#    build_shared_oneshot("liblibname", files, "g++")
#    build_binary_oneshot("name", files, "g++")
  end

#  def install
#  end

#  def uninstall
#  end

end

m = Main.new
